### ISSUE TITLE
redefinition BuglyConfig Buglylog

### ISSUE THREAD

**Issue by ArbifyFun** [BuglyDevTeam/BuglyHotfix-iOS#1]
使用cococapod 同时导入 bugly 与buglyhotfix  在同时引用头文件的时候会出现 重定义问题。发现两个framework中的header 包含了同样的config与log文件。完全没办法同时使用。老司机快开个车

**Comment by szrambo** [comment]
你好，BuglyHotfix 已经集成了Bugly SDK，所以需要去掉Bugly哦
